# frozen_string_literal: true

# SketchUpBuilder — generates a SketchUp .rb script that creates
# components for each panel, adds cutlist attributes, and optionally
# produces an exploded view.
module SketchupBuilder
  # Write a complete SketchUp Ruby script to disk.
  # @param design [Hash] result from EnclosureCalculator.design
  # @param panels [Array<Panel>]
  # @param config [EnclosureConfig]
  # @param client_name [String]
  # @param output_dir [String]
  # @return [Hash] { script: path, skp: path }
  def self.write_script(design, panels, config, client_name, output_dir)
    Dir.mkdir(output_dir) unless Dir.exist?(output_dir)

    safe_name = (client_name || 'JwBox').gsub(/[^a-zA-Z0-9_-]/, '_')
    script_path = File.join(output_dir, "#{safe_name}_cutlist.rb")
    skp_path    = File.join(output_dir, "#{safe_name}_cutlist.skp")

    script_content = generate_script(design, panels, config, client_name, skp_path)
    File.write(script_path, script_content)

    { script: script_path, skp: skp_path }
  end

  # ---- Script generation ----

  def self.generate_script(design, panels, config, client_name, skp_path)
    lines = []
    lines << '# SketchUp Ruby Script — Generated by JwBox'
    lines << "# Date: #{Time.now.strftime('%Y-%m-%d %H:%M')}"
    lines << "# Client: #{client_name}"
    lines << "# Type: #{design[:enclosure_type]}"
    lines << ''
    lines << 'require "sketchup.rb"'
    lines << ''
    lines << '# --- Helper to create a panel component ---'
    lines << 'def jwbox_add_panel(model, name, w, h, x, y, z, thick, cutout_dia = 0, cutout_ox = 0, cutout_oy = 0)'
    lines << '  ent = model.entities'
    lines << '  # Outer face corners'
    lines << '  pts = ['
    lines << '    [x, y, z],'
    lines << '    [x + w, y, z],'
    lines << '    [x + w, y + h, z],'
    lines << '    [x, y + h, z]'
    lines << '  ]'
    lines << '  face = ent.add_face(pts)'
    lines << '  face.pushpull(-thick) if thick > 0'
    lines << ''
    lines << '  # Add cutout if specified'
    lines << '  if cutout_dia > 0'
    lines << '    cx = x + (w / 2.0) + cutout_ox'
    lines << '    cy = y + (h / 2.0) + cutout_oy'
    lines << '    center = Geom::Point3d.new(cx, cy, z)'
    lines << '    radius = cutout_dia / 2.0'
    lines << '    circle = ent.add_circle(center, X_AXIS, radius, 24)'
    lines << '    circle_face = ent.add_face(circle)'
    lines << '    circle_face.pushpull(thick + 0.01)'
    lines << '  end'
    lines << ''
    lines << '  # Make component'
    lines << '  comp = model.definitions.add(name)'
    lines << '  ent.each { |e| comp.entities.add(e) rescue nil }'
    lines << '  comp'
    lines << 'end'
    lines << ''
    lines << 'X_AXIS = Geom::Vector3d.new(1, 0, 0)'
    lines << 'Y_AXIS = Geom::Vector3d.new(0, 1, 0)'
    lines << 'Z_AXIS = Geom::Vector3d.new(0, 0, 1)'
    lines << ''
    lines << '# --- Main ---'
    lines << 'model = Sketchup.active_model'
    lines << 'model.start_operation("JwBox Enclosure", true)'
    lines << ''

    # Add cutlist attributes
    lines << '# Dictionary for cutlist data'
    lines << 'model.set_attribute("JwBox", "type", "' + design[:enclosure_type].to_s + '")'
    lines << 'model.set_attribute("JwBox", "net_volume_cu_ft", ' + design[:net_volume_cu_ft].to_s + ')'
    lines << 'model.set_attribute("JwBox", "target_cu_ft", ' + design[:target_cu_ft].to_s + ')'
    lines << ''

    # Generate panel placement code
    lines << '# Panels'
    panels.each_with_index do |p, i|
      name = "#{p.name}_#{i}"
      w = p.width
      h = p.height
      x = i * 24.0  # offset for exploded view
      y = 0.0
      z = 0.0
      thick = config.material_thickness
      cutout_dia = p.has_cutout ? (p.cutout_diameter || 0) : 0
      cutout_ox = p.cutout_offset_x || 0
      cutout_oy = p.cutout_offset_y || 0

      lines << "jwbox_add_panel(model, '#{name}', #{w}, #{h}, #{x}, #{y}, #{z}, #{thick}, #{cutout_dia}, #{cutout_ox - w/2.0}, #{cutout_oy - h/2.0})"
    end

    lines << ''
    lines << '# --- Port wall ---'
    if design[:port]
      port = design[:port]
      lines << '# Port wall with slot'
      lines << "jwbox_add_panel(model, 'PortWall', #{port[:port_length]}, #{port[:port_height]}, 0, 0, 0, #{config.material_thickness})"
      lines << ''
      lines << '# Slot opening (cut from port wall)'
      lines << 'port_wall_ent = model.entities'
      lines << 'slot_x = 0'
      lines << 'slot_y = 0'
      lines << "slot_w = #{port[:port_width]}"
      lines << "slot_h = #{port[:port_height]}"
      lines << 'slot_pts = [[slot_x, slot_y, 0], [slot_x + slot_w, slot_y, 0], [slot_x + slot_w, slot_y + slot_h, 0], [slot_x, slot_y + slot_h, 0]]'
      lines << 'slot_face = port_wall_ent.add_face(slot_pts)'
      lines << 'slot_face.pushpull(' + config.material_thickness.to_s + ' + 0.01)'
    end

    lines << ''
    lines << '# --- Bracing ---'
    if config.extra_bracing
      lines << '# Horizontal braces'
      int_w = design[:internal][:width] - 2 * config.material_thickness
      int_h = design[:internal][:height] - 2 * config.material_thickness
      lines << "jwbox_add_panel(model, 'HBrace1', #{int_w}, 1.5, 0, #{int_h / 4.0}, #{design[:internal][:depth] / 3.0}, #{config.material_thickness})"
      lines << "jwbox_add_panel(model, 'HBrace2', #{int_w}, 1.5, 0, #{(int_h * 3.0) / 4.0}, #{design[:internal][:depth] / 3.0}, #{config.material_thickness})"
      lines << '# Vertical brace'
      lines << "jwbox_add_panel(model, 'VBrace', 1.5, #{int_h}, #{design[:internal][:width] / 2.0}, 0, #{design[:internal][:depth] / 3.0}, #{config.material_thickness})"
    end

    lines << ''
    lines << '# --- Bandpass divider ---'
    if design[:enclosure_type] == :bandpass_4th
      lines << '# Chamber divider'
      lines << "jwbox_add_panel(model, 'Divider', #{design[:internal][:width]}, #{design[:internal][:height]}, 0, 0, #{design[:internal][:depth] * (1.0 - (config.bandpass_ratio || 0.6))}, #{config.material_thickness})"
    end

    lines << ''
    lines << '# --- Exploded view animation ---'
    lines << 'if defined?(Sketchup::Animation)'
    lines << '  # Simple page-based animation for exploded view'
    lines << '  pages = model.pages'
    lines << '  page = pages.add("Exploded View")'
    lines << '  page.use_hidden_layers = false'
    lines << 'end'
    lines << ''
    lines << 'model.commit_operation'
    lines << ''
    lines << 'UI.messagebox("JwBox: Enclosure created with #{model.definitions.size} components")'
    lines << ''

    lines.join("\n")
  end
end
